# Generated by Django 4.2.6 on 2023-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_genres',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'book_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('BookID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Subtitle', models.CharField(max_length=255)),
                ('Authors', models.CharField(max_length=255)),
                ('Publisher', models.CharField(max_length=255)),
                ('PublicationDate', models.DateField()),
                ('Language', models.CharField(max_length=255)),
                ('StableURl', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
    ]
